spring:
  datasource:
    url: jdbc:sqlite:file_metadata.db
    driver-class-name: org.sqlite.JDBC
    username: ""
    password: ""
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379

server:
  port: 8080
app:
  backup-folder: "backups/"
